CREDITS = {
    "istock_salmon": "Grilled salmon photo by <a href='https://www.istockphoto.com/portfolio/kajakiki?mediatype=photography'>kajakiki</a>",
    "istock_mango": "Mango salsa photo by <a href='https://www.istockphoto.com/portfolio/NatalyHanin?mediatype=photography'>Nataly Hanin</a>",
    "istock_banana1": "Banana smoothie photo by <a href='https://www.istockphoto.com/portfolio/AkayArda?mediatype=photography'>AkayArda</a>",
    "istock_caprese": "Caprese bruschetta photo by <a href='https://www.istockphoto.com/portfolio/AscentXmedia?mediatype=photography'>AscentXmedia</a>",
    "istock_spaghetti": "Spaghetti bolognese photo by <a href='https://www.istockphoto.com/portfolio/GalAmashukeli?mediatype=photography'>Gala Didebashvili</a>",
    "istock_pot_pie": "Chicken pot pie photo by <a href='https://www.istockphoto.com/portfolio/bhofack2?mediatype=photography'>bhofack2</a>",
    "istock_caesar": "Caesar salad photo by <a href='https://www.istockphoto.com/portfolio/Mariha-kitchen?mediatype=photography'>Mariha-kitchen</a>",
    "istock_stroganoff": "Beef stroganoff photo by <a href='https://www.istockphoto.com/portfolio/LeeAnnWhite?mediatype=photography'>LeeAnnWhite</a>",
    "istock_pancakes": "Pancakes photo by <a href='https://www.istockphoto.com/portfolio/bhofack2?mediatype=photography'>bhofack2</a>",
    "istock_yogurt_parfait": "Yogurt parfait photo by <a href='https://www.istockphoto.com/portfolio/jenifoto?mediatype=photography'>jenifoto</a>",
    "unsplash_eggs_benedict": "Eggs benedict photo by <a href='https://unsplash.com/@scotteckersley?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Scott Eckersley</a> on <a href='https://unsplash.com/photos/egg-omelet-on-white-ceramic-plate-yNlMPbRLBTI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Unsplash</a>",
    "unsplash_scrambled_eggs": "Scrambled eggs photo by <a href='https://unsplash.com/@amir_v_ali?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>amirali mirhashemian</a> on <a href='https://unsplash.com/photos/egg-omelet-4gmBIFraSuE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Unsplash</a>",
    "unsplash_chicken_alfredo": "Photo by <a href='https://unsplash.com/@aminrmzni?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>amin ramezani</a> on <a href='https://unsplash.com/photos/a-plate-of-food-XY_qUOa2CdQ?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Unsplash</a>",
    "unsplash_vegetable_bowl": "Photo by <a href='https://unsplash.com/@i_am_simoesse?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Simona Sergi</a> on <a href='https://unsplash.com/photos/sliced-carrots-and-green-vegetable-in-black-ceramic-bowl-QXzUcPen7QM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Unsplash</a>",
    "unsplash_smoothie_bowl": "Photo by <a href='https://unsplash.com/@wesual?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Wesual Click</a> on <a href='https://unsplash.com/photos/strawberry-and-blackberries-on-top-of-brown-table-LymX5D2sSWM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash'>Unsplash</a>",
}
