# Generated by Django 4.2.9 on 2024-01-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.PositiveIntegerField(help_text='In minutes')),
                ('difficulty', models.CharField(max_length=50)),
                ('min_serving_size', models.PositiveIntegerField(help_text='Enter the minimum number of people this would serve.')),
                ('max_serving_size', models.PositiveIntegerField(help_text='Enter the maximum number of people this would serve.')),
                ('type_of_recipe', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=30)),
                ('ingredients', models.TextField(blank=True, default='', help_text='Enter the ingredients for the recipe, separated by commas.', verbose_name='ingredients.Ingredient')),
                ('directions', models.TextField(help_text='Enter the directions for preparing the recipe.')),
                ('pic', models.ImageField(default='no_picture.jpeg', upload_to='recipes')),
            ],
        ),
    ]
