# Generated by Django 4.2.9 on 2024-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.CharField(max_length=255)),
                ('cooking_time', models.PositiveIntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('min_serving_size', models.PositiveIntegerField()),
                ('max_serving_size', models.PositiveIntegerField()),
                ('type_of_recipe', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=30)),
                ('directions', models.TextField()),
            ],
        ),
    ]
