# Generated by Django 4.2.9 on 2024-02-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, default='recipes/no_picture.jpeg', null=True, upload_to='recipes/'),
        ),
    ]
